name: Commit Email
on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      - unlocked
jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Commit Email Check
        uses: semcelik/commit-author-action@master
        with:
          email_domain: 'yieldstreet.com'
          github_token: ${{ secrets.ACTIONS_SECRET }}
          error_on_fail: 'true'