name: DefectDojo Container Scan Integration
on:
  schedule:
    - cron: "0 0 * * 1"   # Runs at 00:00 UTC every Monday
  workflow_dispatch:

jobs:
  run-integration:
    runs-on: self-hosted
    steps:
      - uses: yieldstreet/defect-dojo-connector@v1.0.0
        with:
          integration_name: "container"
          repository: ${{ github.event.repository.name }}
          image_tag: "master"
        env:
          DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_TOKEN }}
          DEFECT_DOJO_API_URL: ${{ vars.DEFECT_DOJO_API_URL }}
          DEFECT_DOJO_PRODUCT_ID: ${{ vars.DEFECT_DOJO_PRODUCT_ID }}
          DEFECT_DOJO_USER_ID: ${{ vars.DEFECT_DOJO_USER_ID }}
          GITHUB_ORG: "yieldstreet"
          DEPENDABOT_CLIENT_ID: ${{ secrets.DEPENDABOT_CLIENT_ID }}
          DEPENDABOT_PRIVATE_KEY: ${{ secrets.DEPENDABOT_PRIVATE_KEY }}
          CODACY_API_URL: ${{ vars.CODACY_API_URL }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
